const FETCH_PRODUCT_FAIL = "FETCH_PRODUCT_FAIL";
const FETCH_PRODUCT_SUCCES = "FETCH_PRODUCT_SUCCES";
const FETCH_PRODUCT_REQUEST = "FETCH_PRODUCT_REQUEST";

export { FETCH_PRODUCT_FAIL, FETCH_PRODUCT_REQUEST, FETCH_PRODUCT_SUCCES };
