const ADD_TO_CART = "ADD_TO_CART";
const ADD_TO_LIKE = "ADD_TO_LIKE";
const REMOVE_TO_CART = "REMOVE_TO_CART";
const REMOVE_TO_LIKE = "REMOVE_TO_LIKE";

export { ADD_TO_CART, ADD_TO_LIKE, REMOVE_TO_CART, REMOVE_TO_LIKE };
